// apps/react-app/src/App.tsx
import React, { useRef, useState } from "react";
import {
  MyButton,
  MyCard,
  MyDialog,
  MyInput,
  MyLayout,
  defineCustomElements,
} from "wc-react-lib";
import { MyInputCustomEvent } from "wc-stencil-lib";

defineCustomElements();

const App: React.FC = () => {
  const [message, setMessage] = useState("");
  const refInput = useRef<HTMLMyInputElement>(null);
  const refDialog = useRef<HTMLMyDialogElement>(null);

  const handleClick = () => {
    if (refInput.current) {
      refInput.current.ExampleMethod("react app üzerinden çağrıldı");
    }
  };

  const onChanc = (e: MyInputCustomEvent<string>) => {
    console.log(e.target.value);
    setMessage(e.target.value);
  };

  const onClickOpenDialog = () => {
    if (refDialog.current) {
      refDialog.current.open(
        () => {
          // ok button callback function
          console.log("ok clicked");
        },
        () => {
          // cancel button callback function
          console.log("cancel clicked");
        }
      );
    }
  };
  return (
    <MyLayout>
      <div slot="header">
        <h4>my-layout header area</h4>
      </div>
      <div slot="sidebar">
        <h4>my-layout sidebar area</h4>
        <h3>React App</h3>
      </div>
      <div slot="content">
        <h4>my-layout content area</h4>

        <MyCard header="Example my-input value and onValueChange">
          <MyInput ref={refInput} value={message} onValueChange={onChanc} />

          <p>model value : {message}</p>
        </MyCard>
        <br />
        <MyCard
          header="Example call component method"
          footer="console üzerinden izlenebilir"
        >
          <MyButton onClick={handleClick} label="my-input Method test" />
        </MyCard>
        <br />
        <MyCard
          header="Example dialog and open method"
          footer="buton clickleri console üzerinden izlenebilir"
        >
          <MyDialog ref={refDialog} >my dialog is opened!</MyDialog>
          <MyButton onClick={onClickOpenDialog} label="Open Dialog"></MyButton>
        </MyCard>
      </div>
    </MyLayout>
  );
};

export default App;

// apps/vue-app/src/App.vue
<script setup>
import { ref, onMounted } from "vue";
import { MyButton, MyInput, MyTable } from "wc-vue-lib";
const message = ref("");
const message1 = ref("");
const refInput = ref();
const refDialog = ref();

function onChange(e) {
  console.log("update:model-value ", e);
}

function onClick() {
  refInput.value.ExampleMethod("vue app üzerinden çağrıldı");
}

function onClickOpenDialog() {
  refDialog.value.open(
    () => {
      // ok button callback function
      console.log("ok clicked");
    },
    () => {
      // cancel button callback function
      console.log("cancel clicked");
    }
  );
}

const columns = ref([
  { key: "id", label: "Id" },
  { key: "name", label: "Name" },
  { key: "surname", label: "Surname" },
  { key: "age", label: "Age" },
  { key: "email", label: "Email" },
]);

const rows = ref([
  {
    name: "harun",
    surname: "Demir",
    age: "29",
    email: "harundemir@thy.com",
    id: "8a04",
  },
  {
    id: "6ee5",
    name: "1",
    surname: "2",
    age: "3",
    email: "4",
  },
  {
    id: "e940",
    name: "3",
    surname: "4",
    age: "5",
    email: "6",
  },
  {
    id: "6998",
    name: "1",
    surname: "3",
    age: "4",
    email: "5",
  },
  {
    id: "cf12",
    name: "Ulaş",
    surname: "Turan",
    age: "27",
    email: "ulas@a.com",
  },
  {
    id: "d71a",
    name: "3",
    surname: "4",
    age: "5",
    email: "6",
  },
]);
</script>

<template>
  <my-layout>
    <div slot="header">
      <h4>my-layout header area</h4>
    </div>
    <div slot="sidebar">
      <h4>my-layout sidebar area</h4>
      <img
        alt="Vue logo"
        class="logo"
        src="./assets/logo.svg"
        width="100"
        height="100"
      />
    </div>
    <div slot="content">
      <h4>my-layout content area</h4>

      <my-card header="Example v-model">
        <my-input ref="refInput" v-model="message" label="Name"></my-input>

        <p>v-model test : {{ message }}</p>
      </my-card>
      <br />
      <my-card
        header="Example update:model-value"
        footer="console üzerinden izlenebilir"
      >
        <my-input
          ref="refInput"
          v-model="message1"
          label="Name"
          @update:model-value="onChange"
        ></my-input>
      </my-card>
      <br />
      <my-card
        header="Example call component method"
        footer="console üzerinden izlenebilir"
      >
        <my-button @click="onClick" label="my-input Method test"></my-button>
      </my-card>
      <br />
      <my-card
        header="Example dialog and open method"
        footer="buton clickleri console üzerinden izlenebilir"
      >
        <my-dialog ref="refDialog"> my dialog is opened! </my-dialog> 
        <my-button @click="onClickOpenDialog" label="dialog"></my-button>
      </my-card>
      <br />
      <my-table :columns="columns" :data="rows" ></my-table>
    </div>
  </my-layout>
</template>
