// apps/react-app/src/App.tsx
import React, { useRef, useState } from "react";
import {
  MyButton,
  MyCard,
  MyDialog,
  MyInput,
  MyLayout,
  defineCustomElements,
} from "wc-react-lib";
import { MyInputCustomEvent } from "wc-stencil-lib";

defineCustomElements();

const App: React.FC = () => {
  const [message, setMessage] = useState("");
  const refInput = useRef<HTMLMyInputElement>(null);
  const refDialog = useRef<HTMLMyDialogElement>(null);

  const handleClick = () => {
    if (refInput.current) {
      refInput.current.ExampleMethod("react app üzerinden çağrıldı");
    }
  };

  const onChanc = (e: MyInputCustomEvent<string>) => {
    console.log(e.target.value);
    setMessage(e.target.value);
  };

  const onClickOpenDialog = () => {
    if (refDialog.current) {
      refDialog.current.open(
        () => {
          // ok button callback function
          console.log("ok clicked");
        },
        () => {
          // cancel button callback function
          console.log("cancel clicked");
        }
      );
    }
  };
  return (
    <MyLayout>
      <div slot="header">
        <h4>my-layout header area</h4>
      </div>
      <div slot="sidebar">
        <h4>my-layout sidebar area</h4>
        <h3>React App</h3>
      </div>
      <div slot="content">
        <h4>my-layout content area</h4>

        <MyCard header="Example my-input value and onValueChange">
          <MyInput ref={refInput} value={message} onValueChange={onChanc} />

          <p>model value : {message}</p>
        </MyCard>
        <br />
        <MyCard
          header="Example call component method"
          footer="console üzerinden izlenebilir"
        >
          <MyButton onClick={handleClick} label="my-input Method test" />
        </MyCard>
        <br />
        <MyCard
          header="Example dialog and open method"
          footer="buton clickleri console üzerinden izlenebilir"
        >
          <MyDialog ref={refDialog} >my dialog is opened!</MyDialog>
          <MyButton onClick={onClickOpenDialog} label="Open Dialog"></MyButton>
        </MyCard>
      </div>
    </MyLayout>
  );
};

export default App;

// packages/angular-workspace/projects/angular-app/src/app/app.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  @ViewChild('myInput') myInput: HTMLMyInputElement | undefined;
  @ViewChild('myDialog') myDialog: HTMLMyDialogElement | undefined;

  title = 'angular-app';
  varTest: string = '';

  onClick() {
    this.myInput?.ExampleMethod('angular üzerinden çağrıldı');
  }

  handleClickValue(value: string) {
    console.log(value);
  }

  onSecretEvent(event: any) {
    console.log(event.detail);
  }

  onClickOpenDialog() {
    this.myDialog?.open(
      () => {
        // ok button callback function
        console.log('ok clicked');
      },
      () => {
        // cancel button callback function
        console.log('cancel clicked');
      }
    );
  }
}

<!-- <my-component first="Your" last="Name"></my-component> -->
<!-- <form > -->
<my-layout>
  <div slot="header">
    <h4>my-layout header area</h4>
  </div>
  <div slot="sidebar">
    <h4>my-layout sidebar area</h4>
    <h3>Angular App</h3>
  </div>
  <div slot="content">
    <h4>my-layout content area</h4>
    <my-card header="Example emit" footer="console üzerinden izlenebilir">
      <my-input
        (value)="(varTest)"
        type="text"
        label="name"
        (secretEvent)="onSecretEvent($event)"
      ></my-input>
    </my-card>
    <br />
    <my-card
      header="Example call component method"
      footer="console üzerinden izlenebilir"
    >
      <my-input
        #myInput
        (value)="(varTest)"
        type="text"
        label="name"
      ></my-input>
      <br />
      <my-button (click)="onClick()" label="call my-input method"></my-button>
    </my-card>
    <br />
    <my-card
      header="Example dialog and open method"
      footer="buton clickleri console üzerinden izlenebilir"
    >
      <my-dialog #myDialog> my dialog is opened! </my-dialog>
      <my-button (click)="onClickOpenDialog()" label="dialog open"></my-button>
    </my-card>

    <router-outlet />
  </div>
</my-layout>
